### ISSUE TITLE
Packages depending on libssl (on debian stretch) fail to properly detect dependencies

### ISSUE THREAD

**Issue by andir** [mmstick/cargo-deb#26]
When building a rust application that depends on libssl `cargo deb` fails to correctly identify the dependencies since the path used by the linker is not the path that `dpkg` knows.

The error I am seeing is:
```
warning: path '/lib/x86_64-linux-gnu/libssl.so.1.1' does not belong to a package: dpkg-query: no path found matching pattern /lib/x86_64-linux-gnu/libssl.so.1.1
 (no auto deps for /builds/foo/target/release/my-project)
```
When checking with `dpkg-query` myself I can confirm the situation.

```
# dpkg-query -S /lib/x86_64-linux-gnu/libssl.so.1.1 
dpkg-query: no path found matching pattern /lib/x86_64-linux-gnu/libssl.so.1.1
```

It looks like in the `libssl` case the file in `/lib/…` is being created by some kind of (multiarch?) trigger during installation of libssl:
```
# dpkg-query -S /usr/lib/x86_64-linux-gnu/libssl.so.1.1 
libssl1.1:amd64: /usr/lib/x86_64-linux-gnu/libssl.so.1.1
```

When looking at the compiled binary it becomes clear why `cargo-deb` selects those files:
```
# ldd target/release/my-project
[…]
	libssl.so.1.1 => /lib/x86_64-linux-gnu/libssl.so.1.1 (0x00007f2f19d6b000)
[…]
```

The files share the same inode so probably a hardlink that was installed by some postinst debian trigger.
```
# stat /lib/x86_64-linux-gnu/libssl.so.1.1
  File: /lib/x86_64-linux-gnu/libssl.so.1.1
  Size: 442920    	Blocks: 872        IO Block: 4096   regular file
Device: 71h/113d	Inode: 7340        Links: 1
Access: (0644/-rw-r--r--)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2017-08-30 15:08:33.773978673 +0000
Modify: 2017-06-05 09:40:42.000000000 +0000
Change: 2017-08-30 15:08:32.547311134 +0000
 Birth: -
# stat /usr/lib/x86_64-linux-gnu/libssl.so.1.1
  File: /usr/lib/x86_64-linux-gnu/libssl.so.1.1
  Size: 442920    	Blocks: 872        IO Block: 4096   regular file
Device: 71h/113d	Inode: 7340        Links: 1
Access: (0644/-rw-r--r--)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2017-08-30 15:08:33.773978673 +0000
Modify: 2017-06-05 09:40:42.000000000 +0000
Change: 2017-08-30 15:08:32.547311134 +0000
 Birth: -
```
Switching the `ld.so.conf` multiarch configuration to first look in `/usr/lib/` doesn't fix the issue since then all other libraries fail.

I am not sure if this a the fault of debian or cargo-deb. Any ideas? I don't mind opening a bug in the debian bug tracker (if libssl is packaged wrong or inconsistent with common practice)

**Comment by pornel** [comment]
Fixed

**Comment by infinity0** [comment]
This is also another reason why generating binary `.deb` packages directly isn't a good idea. You end up having to reduplicate logic that was already written into the Debian buildsystem tools like debhelper etc, in an inaccurate way.

**Comment by andir** [comment]
Well, be it duplicate logic or not: the whole situation still doesn't make sense to me. Why is that one library a special snowflake? I think I tried to get some kind of documentation, reasoning, ... from some Debian people and the best answer I got was "do not know". Do you have some kind of Intel why that is actually required?

Is there sufficient debian tooling for rust packaging these days? Will that (again, as with Golang) require recursive dependency packaging? If its the later then I'd rather use this for in-house, never OSS pieces.. It's sad but I have already wasted so many months packaging the proper way that I just don't care for Debian anymore :/

**Comment by kornelski** [comment]
@infinity0 I use cargo-deb *because* it doesn't use Debian packaging toolchain. I can make a deb for deployment on my server easily without having to install a dozen extra Perl packages. And I can run it with one Cargo command, rather than some combination of several obscure commands with flags and config files.

**Comment by infinity0** [comment]
I've never seen this bug on a Debian system before, so I can't comment. With respect, it's also a common occurence where people mess with their own systems and then blame Debian for it, so I can't say if this is a Debian bug without more information. On my own system that file is installed under `/usr/lib` not `/lib`. Were you experimenting with https://wiki.debian.org/UsrMerge or something? Or do you have a non-standard mount setup? Or did you move files around your own system before and forgot to move them back? Or did you give some non-standard configuration to `/etc/ld.so.conf` or something? Or do you have "custom APT repos" from third-parties that like to screw with the Debian system internals because they can't be bothered reading docs to do it in a clean way that doesn't mess with the Debian system internals?

If you look in `/var/lib/dpkg/info/libssl1.1\:*.post*` you can see it is only restarting some system services, it shouldn't be messing with hard links and Debian would never do such a ridiculous thing anyway.

> Is there sufficient debian tooling for rust packaging these days?

Yes, we just released debcargo which reduces manual maintenance of most packages to a `debian/changelog` and `debian/copyright`.

>  Will that (again, as with Golang) require recursive dependency packaging?

Yes, all distros require this even NixOS. It's a basic QA to make sure everything is FOSS. If you don't care about that then it's too bad, but some people doing FOSS still have quite strong principles about this.

> I can make a deb for deployment on my server easily without having to install a dozen extra Perl packages.

Sure but you also have bugs like this one, and missing features like the lack of `-dbgsym`. Once `debcargo`-packaged crates get going people can just `apt-get install rust-$popular-crate` or just `apt-get source --compile rust-$popular-crate` if they want to compile it from scratch. Also cross-compiling is supported for all Debian rust packages out-of-the-box now, with no extra manual config needed.

> And thanks to being binary package I can deploy Rust programs to servers that don't even have the Rust toolchain.

You could already do this with `cargo build && scp target/debug/whatever your-favourite-host:~/bin`. Not sure what packing this into a `.deb` gains, other than the fact that a Debian system can then install the dependencies correctly, assuming you built this on the same Debian suite (stable vs unstable) as the destination system so that it is indeed linking against the correct shared libraries. Of course when doing this as a `.dsc` source package all the debhelper infrastructure takes care of this automatically so even I as the Debian rust maintainer have never needed to think about it.

**Comment by infinity0** [comment]
Also, if you try to run `cargo-deb` on a non-Debian system and then deploy the resulting `.deb` onto a Debian system you will run into more problems. This is apparently advertised as a "feature" but I'd question if it's been tested other than under very constrained environments. I'd be very surprised if it works reliably. For example if you link a against a Fedora libssl at compile time it's unlikely to work when deployed on an actual Debian system even if you use the same version due to ABI compatibility issues, the compiler version and flags matter and perhaps other things like included headers. If you are lucky it might work, then it might break again later when two systems diverge.

**Comment by andir** [comment]
First let me try to clarify something: I did in no way mean to speak
bad about what the Debian project is doing. I have instead huge respect
of the work that is being done there. I very much believe in FOSS but
can not always meet those standards/requirements within reasonable time and budget
limits (in my professional lives). To make that clear: I would never
willingly violate any of the licenses. I do consider some quality of
life options as offered by this project, if thats compatible with the
big picture.

On 12:20 24.06.18, Ximin Luo wrote:
> I've never seen this bug on a Debian system before, so I can't
> comment. With respect, it's also a common occurence where people mess
> with their own systems and then blame Debian for it, so I can't say if
> this is a Debian bug without more information.

I also never encountered that before. I also haven't tried much
afterwards as I moved jobs and no longer run into that problem.

> On my own system that file is installed under `/usr/lib` not `/lib`.
> Were you experimenting with https://wiki.debian.org/UsrMerge or
> something? Or do you have a non-standard mount setup? Or did you move
> files around your own system before and forgot to move them back? Or
> did you give some non-standard configuration to `/etc/ld.so.conf` or
> something? Or do you have "custom APT repos" from third-parties that
> like to screw with the Debian system internals because they can't be
> bothered reading docs to do it in a clean way that doesn't mess with
> the Debian system internals?

As far as I can recall I did the look at a few Debian systems and
encountered the same issue on all of them. I checked
https://packages.debian.org/stretch/amd64/libssl1.1/filelist, ran the
commands that are mentioned initially and was able to confirm that the
package should not install the mentioned file.

Just now I checked and can no longer reproduce that error. Maybe it was
indeed me being wrong, a faulty system, pkg upgrade or whatever...

> 
> If you look in `/var/lib/dpkg/info/libssl1.1\:*.post*` you can see it is only restarting some system services, it shouldn't be messing with hard links and Debian would never do such a ridiculous thing anyway.

I agree that such insanity should not be done. That was also part of my
confusion an why I opened this bug with the information I was able to
compile back then.

> Yes, we just released debcargo which reduces manual maintenance of most packages to a `debian/changelog` and `debian/copyright`.

:+1: That is awesome! :)
I'll surely look that up for my next (Debian based) rust project.

> 
> >  Will that (again, as with Golang) require recursive dependency packaging?
> 
> Yes, all distros require this even NixOS.

I am not sure how the mentioned debcargo does it but with NixOS you do
not introduce a (rust) package for the entire distribution. You create
list of expressions from the dependencies listed in your Cargo.lock
file. Those dependencies are then only available to the current/depending
package. I suspect debcargo does something similar?

> It's a basic QA to make sure everything is FOSS. If you don't care about that then it's too bad, but some people doing FOSS still have quite strong principles about this.
I do care about FOSS and I am quiet strict about that. There is
unfortunately a growing(?) mob of people that just care for the free as
in free beer part :/ It's their freedom to not share the same opinions
thought...

Still I think a tool like this might be useful if you already have the
means to distribute .deb files to your machines and need to get
something done just now. SCP is not always a viable option.

It is indeed not the proper upstream way of doing things. Did anyone
expect that from this tool? :)

**Comment by infinity0** [comment]
> I am not sure how the mentioned debcargo does it but with NixOS you do not introduce a (rust) package for the entire distribution. You create list of expressions from the dependencies listed in your Cargo.lock file. Those dependencies are then only available to the current/depending package. I suspect debcargo does something similar?

I don't know what you mean by "a rust package for the entire distribution". And whether dependencies are available to outside packages, is a side issue from what was being discussed.

Previously when you said "recursive dependency packaging" I assumed you meant that in order to package some crate, you need to also package all of its dependencies including indirect dependencies. That's true of debcargo and that's true of NixOS as well. Like with Debian, it is possible to create derivations in NixOS that bundle all the dependencies into the package/derivation, but I don't think the official nixpkgs repository allows this, except perhaps in extreme corner cases (same as in Debian).

**Comment by infinity0** [comment]
> It's their freedom to not share the same opinions thought...
Indeed, it's also my freedom to talk about the disadvantages of certain approaches.

> Still I think a tool like this might be useful if you already have the means to distribute .deb files to your machines and need to get something done just now.
There's a lot of things in software engineering history that started off as a way to "get something done just now" and then accumulated a lot of technical debt and became too costly to maintain or improve. People can learn from this and be wise and think things through more carefully from the beginning, be patient and not just "get something done now" because in the long run it actually costs more effort.

**Comment by kornelski** [comment]
> You could already do this with cargo build && scp target/debug/whatever your-favourite-host:~/bin. Not sure what packing this into a .deb gains

It gains major things that deb was created for: checks that dependencies are met, that multiple files are put in the right places, the system tracks which version of the package is installed, and can uninstall it cleanly.

> people can just `apt-get install rust-$popular-crate`

That doesn't work for private/closed-source crates. I use it this way, and I know companies which rely on this too.

**Comment by infinity0** [comment]
> It gains major things that deb was created for: checks that dependencies are met, that multiple files are put in the right places, [..] That doesn't work for private/closed-source crates. I use it this way, and I know companies which rely on this too.

All of these gains and more are realised under a source-package (`.dsc`) based approach.

OTOH, the problems I mentioned with a binary-package (`.deb`) based approach - ABI compatibility, lack of standard Debian features - also exist in a private/closed-source ecosystem if you want to deploy to users on various different Debian-based systems e.g. Debian stable and testing, as well as the different Ubuntu releases every 6 months. These problems are only avoided if you tightly control both the build machines and runtime machines. If that's your use-case that's fine, but when people ask for Debian rust packages, often they have a much wider use-case in mind. Some disclaimers about this would be nice.

**Comment by kornelski** [comment]
> All of these gains and more are realised under a source-package (.dsc) based approach.

IMHO no, it only brings complications. I *have tried* creating "proper" packages before using cargo-deb and gave up. It was easier for me to rewrite/reinvent Debian packaging that to make sense of Debian's packaging Wikis, man pages, and several odd tools spread across multiple Debian packages.

You dropping here and saying how Debian tools for building proper Debian packages are better are like dropping into McDonalds and saying becoming a farmer and raising cows is a better way to make good hamburgers.

**Comment by kornelski** [comment]
> All of these gains and more are realised under a source-package (.dsc) based approach.

I'm not convinced, because it also brings extra build-time dependencies, requirements and build steps. I've tried building proper Debian packages before and I didn't have patience to go through all the docs, and kept running into missing deb-helper commands. I bet that's fixable with enough knowledge and experience, but OTOH `cargo-deb` doesn't require any of that knowledge. I really like that you can run just `cargo deb` and for majority of cases that's the only step, no config, no flags needed.

In this way `cargo-deb` is a "McDonalds" of packaging, so saying that there are more sophisticated ways of achieving the same isn't very relevant.

**Comment by infinity0** [comment]
`cargo-deb` isn't architected to create source packages, so it's not surprising that it would be hard. We've been working on `debcargo` on-and-off which is only oriented towards source packages, and are now starting to use it live in Debian, and realising the gains that I mentioned. The extra build-dependencies are automatically generated and installed, and don't need to be tweaked most of the time, things "work out of the box" just like `cargo-deb`.

t's unfortunate that Debian's documentation is so spread out for sure, but that doesn't mean one does a better job by ignoring it completely. I think the McDonalds analogy is a bit inaccurate because once you eat the hamburger you don't really need to deal with it. This is more like a badly-constructed furniture or tool that might break from time to time. It was very easy for the factory to make, and the production technology was optimised to make it easier for the producers (developers) to quickly construct, but all of these cost savings are instead pushed onto the end-user. So whilst a proper Debian source-based approach is a bit more work for developers - and we've already reduced this by quite a lot - users benefit much more in the end. Everything "just works" as normal, they don't have to worry about ABI compatibility breaking, and they can install debug symbols, everything else that one expects from a Debian package.
